### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by alexlenail** [chikamichi/jquery.circular#1]
Would love to see an example on the github.

**Comment by chikamichi** [comment]
I'm working on it. I extracted this lib as a reusable components for https://github.com/AF83 and beyond. I won't have much spare time for the week coming, but this should land around mid-july.

Out of curiosity: how did you find this project? Not really mainstream ^^

**Comment by alexlenail** [comment]
Hi there,

It was #2 on most recent on jquery.org

On Mon, Jul 8, 2013 at 6:13 PM, Jean-Denis Vauguet <notifications@github.com

> wrote:
> 
> I'm working on it. I extracted this lib as a reusable components for
> https://github.com/AF83 and beyond. I won't have much spare time for the
> week coming, but this should land around mid-july.
> 
> Out of curiosity: how did you find this project? Not really mainstream ^^
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chikamichi/jquery.circular/issues/1#issuecomment-20640240
> .

## 

Alex Lenail
Tufts University '16

**Comment by alexlenail** [comment]
Actually I was about to build one myself, and then I saw this and I thought
it could be something to build off of. But I'm too lazy to look through
everything when it might not be at all what I'm looking for, so I was
hoping for an example.

On Mon, Jul 8, 2013 at 6:29 PM, Alex Lenail alexander.lenail@tufts.eduwrote:

> Hi there,
> 
> It was #2 on most recent on jquery.org
> 
> On Mon, Jul 8, 2013 at 6:13 PM, Jean-Denis Vauguet <
> notifications@github.com> wrote:
> 
> > I'm working on it. I extracted this lib as a reusable components for
> > https://github.com/AF83 and beyond. I won't have much spare time for the
> > week coming, but this should land around mid-july.
> > 
> > Out of curiosity: how did you find this project? Not really mainstream ^^
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/chikamichi/jquery.circular/issues/1#issuecomment-20640240
> > .
> 
> ## 
> 
> Alex Lenail
> Tufts University '16

## 

Alex Lenail
Tufts University '16
